import { useState, useEffect, useRef } from "react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLocation, Link } from "wouter";
import { getLoginUrl } from "@/const";
import {
  ArrowLeft, ArrowRight, BarChart3, Brain, Calendar, CheckCircle,
  ChevronRight, DollarSign, FileText, Loader2, Shield, Sparkles,
  TrendingUp, AlertTriangle, Building2, Users, Zap, Lock
} from "lucide-react";

const INDUSTRIES = [
  "Financial Services / Banking",
  "Healthcare / Life Sciences",
  "Retail / E-commerce",
  "Technology / SaaS",
  "Manufacturing",
  "Telecommunications",
  "Government / Public Sector",
  "Energy / Utilities",
  "Media & Entertainment",
  "Education",
  "Other",
];

const REVENUE_RANGES = [
  "Under $1M",
  "$1M – $10M",
  "$10M – $50M",
  "$50M – $200M",
  "$200M – $1B",
  "Over $1B",
  "Prefer not to say",
];

const TEAM_SIZES = [
  "Solo / 1 person",
  "2–5 people",
  "6–20 people",
  "21–50 people",
  "50+ people",
];

const REGULATIONS = [
  { id: "GDPR", label: "GDPR", desc: "EU data protection" },
  { id: "CCPA", label: "CCPA", desc: "California privacy" },
  { id: "HIPAA", label: "HIPAA", desc: "US healthcare" },
  { id: "SOX", label: "SOX", desc: "Financial reporting" },
  { id: "PCI-DSS", label: "PCI-DSS", desc: "Payment card data" },
  { id: "BCBS239", label: "BCBS 239", desc: "Banking risk data" },
  { id: "ISO27001", label: "ISO 27001", desc: "Info security" },
  { id: "None", label: "None / Unsure", desc: "" },
];

const DRAFT_KEY = "datamind_impact_draft";

export default function DataImpactGenerator() {
  const [, navigate] = useLocation();
  const { isAuthenticated, loading: authLoading } = useAuth();
  const [step, setStep] = useState(1);
  const [form, setForm] = useState({
    problemDescription: "",
    industry: "",
    companyRevenue: "",
    teamSize: "",
    regulations: [] as string[],
  });
  const autoGeneratedRef = useRef(false);
  // Track whether the current generation was triggered automatically (post-login draft restore)
  const [autoGenerateFailed, setAutoGenerateFailed] = useState(false);

  const generate = trpc.dataImpact.generate.useMutation({
    onSuccess: (data) => {
      // Clear the saved draft now that the report is generated
      sessionStorage.removeItem(DRAFT_KEY);
      // Navigate to the report; append conversationId if one was created
      const dest = data.conversationId
        ? `/impact-report/${data.shareToken}?newConversation=${data.conversationId}`
        : `/impact-report/${data.shareToken}`;
      navigate(dest);
    },
    onError: () => {
      // If the auto-generation (post-login) fails, show a retry UI instead of a blank screen
      if (autoGeneratedRef.current) {
        setAutoGenerateFailed(true);
      }
    },
  });

  // On mount: if user is now authenticated and there is a saved draft, restore it and auto-generate
  useEffect(() => {
    if (authLoading || autoGeneratedRef.current) return;
    if (!isAuthenticated) return;
    const raw = sessionStorage.getItem(DRAFT_KEY);
    if (!raw) return;
    try {
      const draft = JSON.parse(raw);
      if (!draft.problemDescription || draft.problemDescription.trim().length < 20) {
        sessionStorage.removeItem(DRAFT_KEY);
        return;
      }
      autoGeneratedRef.current = true;
      // Restore form state and jump straight to step 4 so the user sees the review screen
      setForm(draft);
      setStep(4);
      // Auto-trigger generation immediately
      generate.mutate({
        problemDescription: draft.problemDescription,
        industry: draft.industry || undefined,
        companyRevenue: draft.companyRevenue || undefined,
        teamSize: draft.teamSize || undefined,
        regulations: draft.regulations?.length ? draft.regulations : undefined,
      });
    } catch {
      sessionStorage.removeItem(DRAFT_KEY);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isAuthenticated, authLoading]);

  const toggleRegulation = (id: string) => {
    setForm(prev => {
      if (id === "None") return { ...prev, regulations: ["None"] };
      const without = prev.regulations.filter(r => r !== "None");
      return {
        ...prev,
        regulations: without.includes(id)
          ? without.filter(r => r !== id)
          : [...without, id],
      };
    });
  };

  const canProceed = () => {
    if (step === 1) return form.problemDescription.trim().length >= 20;
    if (step === 2) return form.industry !== "";
    if (step === 3) return true; // optional fields
    return true;
  };

  const handleSubmit = () => {
    generate.mutate({
      problemDescription: form.problemDescription,
      industry: form.industry || undefined,
      companyRevenue: form.companyRevenue || undefined,
      teamSize: form.teamSize || undefined,
      regulations: form.regulations.length ? form.regulations : undefined,
    });
  };

  return (
    <div className="min-h-screen bg-[#080C14] text-white">
      {/* Nav */}
      <nav className="border-b border-white/5 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center gap-4">
          <Link href="/" className="flex items-center gap-2 text-slate-400 hover:text-white transition text-sm">
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </Link>
          <div className="ml-auto flex items-center gap-2 text-sm text-slate-500">
            <span className={step >= 1 ? "text-violet-400 font-medium" : ""}>Problem</span>
            <ChevronRight className="w-3 h-3" />
            <span className={step >= 2 ? "text-violet-400 font-medium" : ""}>Context</span>
            <ChevronRight className="w-3 h-3" />
            <span className={step >= 3 ? "text-violet-400 font-medium" : ""}>Compliance</span>
            <ChevronRight className="w-3 h-3" />
            <span className={step >= 4 ? "text-violet-400 font-medium" : ""}>Generate</span>
          </div>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-violet-500/10 border border-violet-500/20 rounded-full text-violet-300 text-sm mb-5">
            <Sparkles className="w-4 h-4" /> AI-Powered Data Impact Report
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-white mb-3">
            What is your data problem <span className="text-violet-400">costing you?</span>
          </h1>
          <p className="text-slate-400 max-w-xl mx-auto">
            Describe your data challenge and get a financial impact analysis — including cost estimates, regulatory risk, and the ROI of fixing it.
          </p>
        </div>

        {/* Progress bar */}
        <div className="flex gap-2 mb-10">
          {[1, 2, 3, 4].map(s => (
            <div
              key={s}
              className={`h-1 flex-1 rounded-full transition-all ${s <= step ? "bg-violet-500" : "bg-white/10"}`}
            />
          ))}
        </div>

        {/* Step 1: Problem Description */}
        {step === 1 && (
          <div className="space-y-6">
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-2">
                Describe your data problem <span className="text-violet-400">*</span>
              </label>
              <p className="text-xs text-slate-500 mb-3">
                Be as specific as possible. The more detail you provide, the more accurate the financial estimate will be.
              </p>
              <textarea
                value={form.problemDescription}
                onChange={e => setForm(p => ({ ...p, problemDescription: e.target.value }))}
                rows={7}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white placeholder-slate-500 focus:outline-none focus:border-violet-500 text-sm resize-none leading-relaxed"
                placeholder="Example: Our customer database has duplicate records — we estimate 15–20% of our 200,000 customers appear multiple times. This causes our sales team to call the same people twice, our marketing campaigns to send duplicate emails, and our revenue reports to show inflated numbers. We spend about 2 hours per week manually deduplicating records..."
              />
              <div className="flex justify-between mt-1">
                <span className="text-xs text-slate-600">Minimum 20 characters</span>
                <span className={`text-xs ${form.problemDescription.length < 20 ? "text-slate-600" : "text-emerald-500"}`}>
                  {form.problemDescription.length} characters
                </span>
              </div>
            </div>

            {/* Example prompts */}
            <div>
              <p className="text-xs text-slate-500 mb-2">Need inspiration? Try one of these:</p>
              <div className="flex flex-wrap gap-2">
                {[
                  "Duplicate customer records in CRM",
                  "Missing data in financial reports",
                  "Inconsistent product data across systems",
                  "No data lineage or documentation",
                ].map(example => (
                  <button
                    key={example}
                    onClick={() => setForm(p => ({ ...p, problemDescription: p.problemDescription ? p.problemDescription : `Our ${example.toLowerCase()} is causing issues. ` }))}
                    className="text-xs px-3 py-1.5 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-full text-slate-300 transition"
                  >
                    {example}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Step 2: Industry & Company Context */}
        {step === 2 && (
          <div className="space-y-8">
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-3">
                <Building2 className="inline w-4 h-4 mr-1 text-violet-400" />
                What industry are you in? <span className="text-violet-400">*</span>
              </label>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                {INDUSTRIES.map(ind => (
                  <button
                    key={ind}
                    onClick={() => setForm(p => ({ ...p, industry: ind }))}
                    className={`text-sm px-3 py-2.5 rounded-lg border text-left transition ${
                      form.industry === ind
                        ? "bg-violet-600/20 border-violet-500 text-violet-200"
                        : "bg-slate-900 border-slate-700 text-slate-300 hover:border-slate-500"
                    }`}
                  >
                    {ind}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-200 mb-3">
                <DollarSign className="inline w-4 h-4 mr-1 text-violet-400" />
                Annual company revenue <span className="text-slate-500 font-normal">(optional — helps calibrate estimates)</span>
              </label>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                {REVENUE_RANGES.map(rev => (
                  <button
                    key={rev}
                    onClick={() => setForm(p => ({ ...p, companyRevenue: rev }))}
                    className={`text-sm px-3 py-2.5 rounded-lg border text-left transition ${
                      form.companyRevenue === rev
                        ? "bg-violet-600/20 border-violet-500 text-violet-200"
                        : "bg-slate-900 border-slate-700 text-slate-300 hover:border-slate-500"
                    }`}
                  >
                    {rev}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-200 mb-3">
                <Users className="inline w-4 h-4 mr-1 text-violet-400" />
                Data team size <span className="text-slate-500 font-normal">(optional)</span>
              </label>
              <div className="flex flex-wrap gap-2">
                {TEAM_SIZES.map(size => (
                  <button
                    key={size}
                    onClick={() => setForm(p => ({ ...p, teamSize: size }))}
                    className={`text-sm px-4 py-2 rounded-lg border transition ${
                      form.teamSize === size
                        ? "bg-violet-600/20 border-violet-500 text-violet-200"
                        : "bg-slate-900 border-slate-700 text-slate-300 hover:border-slate-500"
                    }`}
                  >
                    {size}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Step 3: Regulations */}
        {step === 3 && (
          <div className="space-y-6">
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-2">
                <Shield className="inline w-4 h-4 mr-1 text-violet-400" />
                Which regulations apply to your business?
              </label>
              <p className="text-xs text-slate-500 mb-4">
                This helps us flag specific compliance risks and fine exposure in your report. Select all that apply.
              </p>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {REGULATIONS.map(reg => (
                  <button
                    key={reg.id}
                    onClick={() => toggleRegulation(reg.id)}
                    className={`text-sm px-3 py-3 rounded-xl border text-left transition ${
                      form.regulations.includes(reg.id)
                        ? "bg-violet-600/20 border-violet-500 text-violet-200"
                        : "bg-slate-900 border-slate-700 text-slate-300 hover:border-slate-500"
                    }`}
                  >
                    <div className="font-semibold">{reg.label}</div>
                    {reg.desc && <div className="text-xs text-slate-500 mt-0.5">{reg.desc}</div>}
                  </button>
                ))}
              </div>
            </div>

            <Card className="bg-slate-900/50 border-slate-700">
              <CardContent className="p-4">
                <div className="flex gap-3">
                  <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-slate-200 mb-1">Why this matters</p>
                    <p className="text-xs text-slate-400 leading-relaxed">
                      GDPR fines alone have exceeded €4.9 billion since 2018. Your report will include specific regulatory articles that may apply to your data problem, along with the potential fine exposure — so you can present the risk in financial terms to your leadership.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Step 4: Login gate + Review & Generate */}
        {step === 4 && !authLoading && !isAuthenticated && (
          <div className="space-y-6 text-center">
            <div className="w-16 h-16 rounded-2xl bg-violet-600/20 border border-violet-500/30 flex items-center justify-center mx-auto">
              <Lock className="w-7 h-7 text-violet-400" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white mb-2">Create a free account to get your report</h2>
              <p className="text-slate-400 text-sm max-w-md mx-auto leading-relaxed">
                Your report is ready to generate. Sign up for free — no credit card required — to save it, share it, and access it anytime.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <Button
                className="bg-violet-600 hover:bg-violet-700 text-white px-8 gap-2"
                onClick={() => {
                  sessionStorage.setItem(DRAFT_KEY, JSON.stringify(form));
                  navigate("/register?returnTo=/impact");
                }}
              >
                <Sparkles className="w-4 h-4" /> Sign up free & generate report
              </Button>
              <Button
                variant="outline"
                className="border-slate-700 text-slate-300 hover:text-white hover:bg-slate-800 px-8"
                onClick={() => {
                  sessionStorage.setItem(DRAFT_KEY, JSON.stringify(form));
                  navigate("/login?returnTo=/impact");
                }}
              >
                Already have an account? Sign in
              </Button>
            </div>
            <p className="text-xs text-slate-600">Your answers are saved — you won't need to fill the form again after signing in.</p>
          </div>
        )}

        {step === 4 && (authLoading || isAuthenticated) && (
          <div className="space-y-6">
            <div className="bg-slate-900 border border-slate-700 rounded-xl p-5 space-y-4">
              <h3 className="font-semibold text-white mb-3">Report Summary</h3>

              <div>
                <p className="text-xs text-slate-500 uppercase tracking-wider mb-1">Data Problem</p>
                <p className="text-sm text-slate-300 leading-relaxed line-clamp-4">{form.problemDescription}</p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-xs text-slate-500 uppercase tracking-wider mb-1">Industry</p>
                  <p className="text-sm text-slate-300">{form.industry || "Not specified"}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500 uppercase tracking-wider mb-1">Revenue</p>
                  <p className="text-sm text-slate-300">{form.companyRevenue || "Not specified"}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500 uppercase tracking-wider mb-1">Team Size</p>
                  <p className="text-sm text-slate-300">{form.teamSize || "Not specified"}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500 uppercase tracking-wider mb-1">Regulations</p>
                  <p className="text-sm text-slate-300">
                    {form.regulations.length ? form.regulations.join(", ") : "Not specified"}
                  </p>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {[
                { icon: DollarSign, label: "Financial Cost Estimate", desc: "Annual cost range based on Gartner & IBM benchmarks", color: "text-emerald-400" },
                { icon: Shield, label: "Regulatory Risk Flags", desc: "Specific regulations and fine exposure amounts", color: "text-amber-400" },
                { icon: TrendingUp, label: "Fix ROI Projection", desc: "Estimated return if the problem is resolved", color: "text-violet-400" },
              ].map(item => (
                <div key={item.label} className="bg-slate-900 border border-slate-700 rounded-xl p-4 text-center">
                  <item.icon className={`w-6 h-6 ${item.color} mx-auto mb-2`} />
                  <p className="text-sm font-medium text-white mb-1">{item.label}</p>
                  <p className="text-xs text-slate-500">{item.desc}</p>
                </div>
              ))}
            </div>

            {generate.error && (
              <div className="bg-red-900/20 border border-red-500/30 rounded-xl p-4 text-sm text-red-300">
                Something went wrong generating your report. Please try again.
              </div>
            )}
          </div>
        )}

        {/* Navigation */}
        <div className="flex justify-between mt-10">
          {step > 1 ? (
            <Button
              variant="outline"
              onClick={() => setStep(s => s - 1)}
              className="border-slate-700 text-slate-300 hover:text-white hover:bg-slate-800"
              disabled={generate.isPending}
            >
              <ArrowLeft className="w-4 h-4 mr-2" /> Back
            </Button>
          ) : (
            <div />
          )}

          {step < 4 ? (
            <Button
              onClick={() => setStep(s => s + 1)}
              disabled={!canProceed()}
              className="bg-violet-600 hover:bg-violet-700 text-white px-6"
            >
              Continue <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          ) : (
            <Button
              onClick={handleSubmit}
              disabled={generate.isPending}
              className="bg-violet-600 hover:bg-violet-700 text-white px-8 gap-2"
            >
              {generate.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating Report...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  Generate My Report
                </>
              )}
            </Button>
          )}
        </div>

        {generate.isPending && (
          <div className="mt-8 text-center">
            <div className="inline-flex flex-col items-center gap-3 px-6 py-5 bg-slate-900 border border-violet-500/20 rounded-xl">
              <Loader2 className="w-8 h-8 text-violet-400 animate-spin" />
              <div>
                <p className="text-sm font-medium text-white">Analysing your data problem...</p>
                <p className="text-xs text-slate-500 mt-1">Applying Infonomics valuation models and regulatory frameworks</p>
              </div>
              <div className="flex gap-4 text-xs text-slate-500">
                <span className="flex items-center gap-1"><CheckCircle className="w-3 h-3 text-emerald-500" /> Gartner benchmarks</span>
                <span className="flex items-center gap-1"><CheckCircle className="w-3 h-3 text-emerald-500" /> DAMA-DMBOK</span>
                <span className="flex items-center gap-1"><CheckCircle className="w-3 h-3 text-emerald-500" /> Infonomics models</span>
              </div>
            </div>
          </div>
        )}
        {/* Failure recovery: shown when auto-generation after login fails */}
        {autoGenerateFailed && !generate.isPending && (
          <div className="mt-8 bg-red-900/20 border border-red-500/30 rounded-xl p-5 text-center space-y-3">
            <p className="text-sm font-medium text-red-300">Something went wrong generating your report automatically.</p>
            <p className="text-xs text-slate-500">Your form data is still saved. Click below to try again.</p>
            <Button
              onClick={() => {
                setAutoGenerateFailed(false);
                handleSubmit();
              }}
              className="bg-violet-600 hover:bg-violet-700 text-white px-6 gap-2"
            >
              <Sparkles className="w-4 h-4" /> Retry Report Generation
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
